### ISSUE TITLE
Performance issue when inserting node

### ISSUE THREAD

**Issue by Abbasi-Waqas** [bwrrp/slimdom.js#126]
Inserting node into parent's children is using O(N) time complexity in this [function] and it is leading to performance issues (https://github.com/bwrrp/slimdom.js/blob/8bce43a71075ebebb451e07a081bc60e24ea5777/src/util/treeMutations.ts#L18)

This is  most likely caused by [Line 33](https://github.com/bwrrp/slimdom.js/blob/8bce43a71075ebebb451e07a081bc60e24ea5777/src/util/treeMutations.ts#L33) where indexOf is not constant-time and inserting the node into the childNodes array is also not constant (O(N) worst-case)

Possible fix for indexOf is to keep track of the indices of a node's children in a Map / Object using some sort of id mapped to the index in the childNodes array.

**Comment by bwrrp** [comment]
I think that if we want to continue to expose `childNodes` as an array, we can't really get rid of the O(N) update cost there. I'm going to close this issue for now, but I'll leave your PR open for future performance tests to build on.
