### ISSUE TITLE
Range#extractContents and Range#insertNode

### ISSUE THREAD

**Issue by MattIPv4** [bwrrp/slimdom.js#137]
Hey!

This is an amazing library -- I've been poking around at it and specifically looking at using ranges as very few Node-supported DOM implementations have them.

It'd be utterly awesome if this library was able to implement support for extractContents and insertNode on Ranges <3

Cheers :)

**Comment by bwrrp** [comment]
Hi, sorry for the lack of reply! I've just released 3.1.0 which adds all of the missing methods on Range. Hope this helps!

**Comment by jkonowitch** [comment]
Just expressing my appreciation for this library. It is _perfect_ for my use case, as it requires lots of server side processing of `Range`s. JSDOM is wayyy too heavy, and other libraries like [linkedom](https://github.com/WebReflection/linkedom) are faster but do not support the full Range API and that implementation is not as well tested. Combined with `fontoxpath`, this solution is fantastic.
