### ISSUE TITLE
Please return error location information in errors

### ISSUE THREAD

**Issue by rrthomas** [bwrrp/slimdom.js#151]
Error messages and objects do not contain any location info that I can see.

I tried using `DOMParser` instead, but in my case that doesn't work, as I want to parse fragments. I tried using a range with `createContextualFragment`, but slimdom doesn't implement that method.

Thanks for slimdom! I would like to be able to return more helpful errors to users of my code who submit badly-formed XML, hence the location would be most handy. I think my workaround for now will be to use an external tool such as `tidy`.

**Comment by bwrrp** [comment]
Hi,

Most of the errors that can be thrown by the parser should already contain the line and column number as part of the message. Would it help if I also expose those on the error object itself, or are you seeing an error that does not yet have this info at all?

As for `createContextualFragment`, my understanding is that it's pretty much equivalent to the current `parseXmlFragment` function if you set the `resolveNamespacePrefix` option to call `range.startContainer.lookupNamespaceURI` - or do you also need to resolve custom entities in these fragments?

**Comment by rrthomas** [comment]
I am seeing an error that does not have this info: for `is missing a closing tag`. At least, I can't see a position in the error message, nor in the information supplied to the (plain) `Error` constructor (sorry if I'm missing something!).

Thanks for the explanation of `createContextualFragment`, I was only trying to use it to get error locations. `parseXmlFragment` with locations is fine if that works.

**Comment by rrthomas** [comment]
Here is the source code from current git:

```ts
                if (!domContext.entityRoot) {
                        throw new Error(
                                `${
                                        entityContext.entity
                                                ? `replacement text for entity 
"${entityContext.entity}"`
                                                : into === doc
                                                ? 'document'
                                                : 'fragment'
                                } is not well-formed - element "${
                                        domContext.root.nodeName
                                }" is missing a closing tag`
                        );
                }
```

**Comment by bwrrp** [comment]
Ah, thanks, that is indeed one of the few errors that doesn't have a location yet. As the whole point of that  error is that there is no end tag to highlight, I guess the most appropriate location to show here would be that of the corresponding start tag?

**Comment by rrthomas** [comment]
Yes, that sounds ideal!
