### ISSUE TITLE
Bundle typescript definitions

### ISSUE THREAD

**Issue by bwrrp** [bwrrp/slimdom.js#56]
It would be nice if we could bundle a .d.ts with the slimdom typings. The typescript compiler generates .d.ts files for each source file, but I'd prefer to bundle a single file and omit typings for private implementation details. 

https://github.com/timocov/dts-bundle-generator may be an option, but currently seems to be incompatible with the default exports used in the codebase. Maybe if changing these to named will be enough?

**Comment by bwrrp** [comment]
Also consider api-extractor, which can also be used for generating documentation:

https://github.com/Microsoft/web-build-tools/wiki/API-Extractor-~-Creating-.d.ts-rollups
https://github.com/Microsoft/web-build-tools/wiki/API-Extractor-~-Rendering-API-docs

**Comment by timocov** [comment]
Hi there!

> but currently seems to be incompatible with the default exports used in the codebase

Actually it works with default exports, but only if you have exactly the same name of export and all imports (for example if you have `export default class MyClass` then you need to have `import MyClass from '';` everywhere else).

I just run it via `npx dts-bundle-generator --project tsconfig.build.json src/index.ts` and seems that it generates correct declaration without errors 🙂

**Comment by bwrrp** [comment]
Thanks for the update, that's great to hear! I'll make sure to try dts-bundle-generator again when I have time to revisit this.

**Comment by bwrrp** [comment]
A `slimdom.d.ts` bundle will be included in 2.3
